export const RECRUIT_TEAMS_REQUEST = 'RECRUIT_TEAMS_REQUEST';
export const RECRUIT_TEAMS_SUCCESS = 'RECRUIT_TEAMS_SUCCESS';
export const RECRUIT_TEAMS_FAIL = 'RECRUIT_TEAMS_FAIL';

export const PROGRESS_TEAMS_REQUEST = 'PROGRESS_TEAMS_REQUEST';
export const PROGRESS_TEAMS_SUCCESS = 'PROGRESS_TEAMS_SUCCESS';
export const PROGRESS_TEAMS_FAIL = 'PROGRESS_TEAMS_FAIL';